import platform
import os


def get_platform():
    system = platform.system().lower()
    
    if system == 'windows':
        return 'windows'
    elif system == 'linux':
        if is_termux():
            return 'termux'
        return 'linux'
    else:
        return 'unknown'


def is_windows():
    return get_platform() == 'windows'


def is_linux():
    return get_platform() == 'linux'


def is_termux():
    if os.environ.get('PREFIX', '').startswith('/data/data/com.termux'):
        return True
    
    if os.path.exists('/data/data/com.termux/files/usr'):
        return True
    
    return False


def is_macos():
    return get_platform() == 'macos'


def get_install_directory():
    current_platform = get_platform()
    
    if current_platform == 'windows':
        return os.path.join(os.environ.get('APPDATA', ''), 'GitGo')
    
    elif current_platform == 'termux':
        prefix = os.environ.get('PREFIX', '/data/data/com.termux/files/usr')
        return os.path.join(prefix, 'share', 'gitgo')
    
    elif current_platform == 'linux' or current_platform == 'macos':
        home = os.path.expanduser('~')
        return os.path.join(home, '.local', 'share', 'gitgo')
    
    else:
        return os.path.expanduser('~/.gitgo')


def get_bin_directory():
    current_platform = get_platform()
    
    if current_platform == 'windows':
        potential_paths = [
            os.path.expanduser("~\\AppData\\Local\\Microsoft\\WindowsApps"),
            "C:\\Windows\\System32",
            os.path.expanduser("~\\bin")
        ]
        
        for path in potential_paths:
            if os.path.exists(path) and os.access(path, os.W_OK):
                return path
        
        fallback = os.path.expanduser("~\\bin")
        os.makedirs(fallback, exist_ok=True)
        return fallback
    
    elif current_platform == 'termux':
        prefix = os.environ.get('PREFIX', '/data/data/com.termux/files/usr')
        return os.path.join(prefix, 'bin')
    
    elif current_platform == 'linux' or current_platform == 'macos':
        home = os.path.expanduser('~')
        bin_dir = os.path.join(home, '.local', 'bin')
        os.makedirs(bin_dir, exist_ok=True)
        return bin_dir
    
    else:
        return os.path.expanduser('~/bin')


def get_executable_name():
    if is_windows():
        return 'gitgo.bat'
    else:
        return 'gitgo'


def get_path_separator():
    if is_windows():
        return ';'
    else:
        return ':'


def get_python_executable():
    if is_windows():
        return 'python'
    else:
        import shutil
        if shutil.which('python3'):
            return 'python3'
        elif shutil.which('python'):
            return 'python'
        else:
            return 'python3'


def create_wrapper_script(script_path, install_dir):
    current_platform = get_platform()
    
    if current_platform == 'windows':
        return f'@echo off\npy "{script_path}" %*\nexit /b %errorlevel%\n'
    
    else:
        python_exec = get_python_executable()
        return f'''#!/bin/sh
# GitGo CLI Wrapper
# Auto-generated by GitGo installer

exec {python_exec} "{script_path}" "$@"
'''


def is_in_path(directory):
    path_env = os.environ.get('PATH', '')
    separator = get_path_separator()
    
    path_dirs = [os.path.normpath(p) for p in path_env.split(separator)]
    normalized_dir = os.path.normpath(directory)
    
    return normalized_dir in path_dirs


def get_shell_config_files():
    if is_windows():
        return []  
    
    home = os.path.expanduser('~')
    
    config_files = [
        os.path.join(home, '.bashrc'),
        os.path.join(home, '.bash_profile'),
        os.path.join(home, '.zshrc'),
        os.path.join(home, '.profile'),
    ]
    
    return [f for f in config_files if os.path.exists(f)]


def get_platform_display_name():
    current_platform = get_platform()
    
    names = {
        'windows': 'Windows',
        'linux': 'Linux',
        'termux': 'Termux (Android)',
        'macos': 'macOS',
        'unknown': 'Unknown Platform'
    }
    
    return names.get(current_platform, 'Unknown Platform')
